/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type { IBank, IBankInterface } from "../../Bank.sol/IBank.js";

const _abi = [
  {
    inputs: [
      {
        internalType: "contract IERC20",
        name: "token",
        type: "address",
      },
      {
        internalType: "address",
        name: "to",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "transfer",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "contract IERC721",
        name: "token",
        type: "address",
      },
      {
        internalType: "address",
        name: "to",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
    ],
    name: "transferERC721",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IBank__factory {
  static readonly abi = _abi;
  static createInterface(): IBankInterface {
    return new Interface(_abi) as IBankInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): IBank {
    return new Contract(address, _abi, runner) as unknown as IBank;
  }
}
