/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IRepository__factory } from "./IRepository__factory.js";
export { Repository__factory } from "./Repository__factory.js";
