/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { MockERC20__factory } from "./MockERC20__factory.js";
export { MockERC721__factory } from "./MockERC721__factory.js";
