/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IStakes__factory } from "./IStakes__factory.js";
export { Stakes__factory } from "./Stakes__factory.js";
