/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  RepositoryUser,
  RepositoryUserInterface,
} from "../RepositoryUser.js";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_repository",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    inputs: [],
    name: "UnauthorizedRepoCall",
    type: "error",
  },
  {
    inputs: [],
    name: "repository",
    outputs: [
      {
        internalType: "contract IRepository",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class RepositoryUser__factory {
  static readonly abi = _abi;
  static createInterface(): RepositoryUserInterface {
    return new Interface(_abi) as RepositoryUserInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): RepositoryUser {
    return new Contract(address, _abi, runner) as unknown as RepositoryUser;
  }
}
